### PR TITLE
Allow client applications to request no scopes

### PR DESCRIPTION
**Pull request by cpapazian**
note: client applications are already allowed to request no scope. everything will just work. this PR is to let users create client applications that CANNOT request scopes.

### CODE REVIEW

**Comment by cpapazian** [comment]
@jackiekazil or @yozlet, can i get some code review?

**Comment by cpapazian** [comment]
@yozlet @jackiekazil should i just go ahead and merge this?

**Comment by yozlet** [comment]
So I'm guessing that an actual request would just not have a `scopes` parameter?

**Comment by cpapazian** [comment]
yes. we support this already, but there is no way to create a client application that has no scopes.

**Comment by adelevie** [comment]
I almost have my head wrapped around this, @cpapazian. I'm thinking this feature should have a UI component (user selects "no scope" when creating the application). I'm sure there's a reason why that's not the case, but could you explain this part to me?

**Comment by cpapazian** [comment]
it does have a UI component. Previously, if you created an application, but did not select any scope, it would give a validation error. With this patch, the validation is successful.

**Comment by adelevie** [comment]
LGTM

**Pull request merged**
