### PR TITLE
Feature/accessibility testing

### PR DESCRIPTION
**Pull request by adelevie**
WIP

### CODE REVIEW

**Comment by adelevie** [comment]
This is good to merge now (after some code review), but more things that can be added:

- [] set a max threshold for warnings
- [] apply the test sitewide. Currently, it's only testing the homepage.

**Comment by jackiekazil** [comment]
@yozlet would you be able to look at this?

**Comment by adelevie** [comment]
I should note that it is not ready (is there a tag for that?). I discovered that ra11y/pa11y is reporting some false negatives as implemented here.

**Comment by adelevie** [comment]
For some reason it's reporting false negatives. I need to investigate and fix.

**Comment by jackiekazil** [comment]
@adelevie marked it develop since it isn't ready. When you are ready, mark it accept and alert yoz

**Comment by adelevie** [comment]
Closing this in favor of a better approach.

**Pull request closed without merging**
