### PR TITLE
sms 2fa form should show mobile number

### PR DESCRIPTION
**Pull request by cpapazian**

### CODE REVIEW

**Comment by cpapazian** [comment]
@yozlet can you take a look?

**Comment by yozlet** [comment]
Not sure about showing the mobile number - I wonder if it'd be better to show only, say, the last four digits. But maybe that's me being paranoid again.
/cc @jackiekazil - any opinion?

**Comment by jackiekazil** [comment]
6 of 1 / 1/2 dozen of other -- it could go either way with me -- I could see a valid argument for either.  I would say that the final decision should be user driven. Not to pass the buck, but @esgoodman, do you have some user insight / 2 cents on this?

**Comment by esgoodman** [comment]
i have no great user-driven insights. I just did some searching and don't see any data publicly available.

**Comment by jackiekazil** [comment]
Let's leave it as is and try to get user feedback on if there is preference by users. 
@yozlet otherwise, do you feel good with merging this?

**Comment by jackiekazil** [comment]
@yozlet ignore my last comment. Since this is still open, after doing some reading on the topic, I am going to say -- let's obscure. 

@cpapazian -- can you update to only reveal the last four digits?

**Comment by cpapazian** [comment]
@yozlet done

**Comment by cpapazian** [comment]
@yozlet @jackiekazil should i just go ahead and merge this?

**Comment by jackiekazil** [comment]
After a quick review -- looks good to me. Go ahead and merge.

**Pull request merged**
