### PR TITLE
Update master (mid-March 2015)

### PR DESCRIPTION
**Pull request by yozlet**
Everything added to devel since master was last updated (mid-January).

Includes:
* Lots of documentation improvements
* ToS & Privacy links for applications
* Public-facing PRA/OMB requirements
* Better error-handling
* Scopeless application authorizations
* Misc. other fixes
* Buckets of love

@jackiekazil or @adelevie, please review & merge!

### CODE REVIEW

**Comment by jackiekazil** [comment]
I didn't see any buckets of love when I looked over it. 
(I would merge, but I am going to assign @adelevie, just incase he wants to review.)

**Comment by adelevie** [comment]
Looks fine to me. How thorough of a review do we want here?

**Comment by jackiekazil** [comment]
@yoz, this is a merge of code that has already been reviewed in another
capacity yes?

**Comment by yozlet** [comment]
@jackiekazil Yep!

**Comment by adelevie** [comment]
LGTM

**Pull request merged**
