### PR TITLE
Feature/allow user to require 2fa

### PR DESCRIPTION
**Pull request by cpapazian**
allow user to specify that 2fa is required

https://github.com/18F/myusa/issues/398

### CODE REVIEW

**Comment by cpapazian** [comment]
@polastre check it out.

**Comment by cpapazian** [comment]
@yozlet can you take a look?

**Comment by polastre** [comment]
This looks good to me.

**Comment by yozlet** [comment]
:+1:

**Comment by polastre** [comment]
Shipping it! :boat:

**Pull request merged**
