### PR TITLE
Need to be able to see all apps as admin

### PR DESCRIPTION
**Pull request by cpapazian**
Tabs for "all" and "pending approval" as well as a search input that does a wildcard query on `application.name` ... can add more searchiness later.

### CODE REVIEW

**Comment by cpapazian** [comment]
@yozlet can you take a look?

**Comment by polastre** [comment]
Looking at this now...

**Comment by polastre** [comment]
This works, but a few quick fixes:

- The search box is cleared after a search, so you don't know you're in a search.  Either:
  - the search term should stay in the search box
  - or, there should be a way to clear your search

- Is there any way to show the owner of the application, such as their email address?  It would be nice to be able to contact someone about their application before making it public.

**Comment by cpapazian** [comment]
had to jump through some hoops to get the owner email to show up ... the whole roles system i put together makes the relationship between user and applications a mess. could add back in a foreign key to user/owner, while still maintaining the roles for other things (like developers) which would simplify this.

**Comment by polastre** [comment]
Let's ship it and test it on staging.  Sounds like there could be cleaner ways to do this, but if it work then it works.

**Pull request merged**
