### PR TITLE
New landing page design

### PR DESCRIPTION
**Pull request by adelevie**
We're making a new homepage, following the content & design iterations in #576. See the original [Sketch and PNG files](http://goo.gl/Zmx57k).

### CODE REVIEW

**Comment by adelevie** [comment]
@mkhandekar, I've given Bourbon+Refills a try and I like it a lot so far. I generated a scaffold of the homepage that I now need to customize. To get this working on your machine, run the following:

```
git checkout feature/redesign
git pull origin feature/redesign
bundle
``` 

If you look at `redesign.html.erb`, you'll see that it's just calling `render` a few times. The actual code for these partials is in `app/views/refills` and the stylesheets are in `app/assets/stylesheets/refills`.

**Comment by adelevie** [comment]
@mkhandekar, what should the hover color the nav bar links be?

**Comment by juliaelman** [comment]
Next steps are updating colors for accessibility purposes and adding link to new learn more page. See #601 for reference. //cc @jackiekazil @mkhandekar

**Comment by jackiekazil** [comment]
:+1:

**Comment by mkhandekar** [comment]
@juliaelman 

Here are the updated colors for the landing page. Please check:
* top nav typography & color
* Learn More & Sign Up Now button colors
* Icon colors
* 1, 2, 3 numbers

15-04-10_landing

**Comment by juliaelman** [comment]
@mkhandekar awesome and thank you! Would it be possible to get a link to the Sketch file to make sure there are no color conversion issues?

**Comment by juliaelman** [comment]
@mkhandekar I updated the code base with the changes from your Sketch. :fireworks: When you get a chance, feel free to pull down the changes to make sure that they look okay!

**Comment by mkhandekar** [comment]
:+1: looks great! Just a heads up, as we get some of the other pages ready, we'll come back to the landing page to adjust the styles of some of the UI elements (buttons, etc).

**Comment by juliaelman** [comment]
Noting here for future reference, this page lives at the `/redesign` route. Once the learn more page is completed (#601) we should add that route to the new landing page and we'll be good to go live.

**Pull request merged**
