### PR TITLE
Patch of Doorkeeper to create application UID, secret when blank (not just nil)

### LINKED ISSUE #682: Users are unable to create new applications
The staging server throws an exception whenever a user attempts to create a new application. The error presented on the page

> Whoops! Check your form for possible errors

suggests the issue is an invalid field in the form. But instead, the issue seems to be an error generating the UID and Secret for the application.

### PR DESCRIPTION
**Pull request by harrisj**
A local monkeypatch of Doorkeeper to fix issue #682

### CODE REVIEW

**Comment by harrisj** [comment]
Okay, this is where it gets bizarre. This was a bug I found when running a dump of the staging DB locally. This problem is also on the new staging server. However, when I dump the DB completely and rebuild it using `rake db:setup` there is no error creating a new application even without this PR. There is something specific to the staging database that is triggering this problem.

**Comment by harrisj** [comment]
Found the issue that explains why this is only an issue on staging. Here is what the schema looks like for a dump generated by `rake db:structure:dump`

```sql
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `uid` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
```

and this is what an excerpt of the schema generated by the Mac MySQL client Sequel Pro looks like (what was used to dump the data that was loaded into staging)

```sql
  `uid` varchar(255) CHARACTER SET utf8 NOT NULL DEFAULT '',
  `secret` varchar(255) CHARACTER SET utf8 NOT NULL DEFAULT '',
```

Note that it is explicitly forcing those columns to an empty string as a default. Is this a change that was made in the source DB or is this something that Sequel is doing to be helpful. This explains why the code works on most DBs and suddenly stopped working. Argh.

I am a bit inclined to keep the monkey patch, just because an empty uid or secret string is still an error in some case and should trigger generation, but this is just my own opinion. This seems to be why the problem suddenly struck us.

**Comment by harrisj** [comment]
Technically, I fixed a problem that isn't necessarily going to happen again, but we might want to keep this monkey patch in there

**Comment by yozlet** [comment]
:+1:

Let's kill this once the DK folks have merged it and we've upgraded DK.

**Pull request merged**
