### PR TITLE
Use https for links in email confirmation

### PR DESCRIPTION
**Pull request by adelevie**
WIP, tough to test locally.

### CODE REVIEW

**Comment by jessieay** [comment]
Looks like this project is on Rails 4.1, which includes actionmailer previews. You could use that to make sure the links are showing up as `https` properly. http://richonrails.com/articles/action-mailer-previews-in-ruby-on-rails-4-1

:rainbow:

**Comment by adelevie** [comment]
Thanks, @jessieay! Much appreciated!

**Comment by jackiekazil** [comment]
@adelevie what is the current status of this?

**Comment by adelevie** [comment]
@yozlet this is ready to go, take a look if you want.

**Pull request merged**
