### PR TITLE
Updated Contact Us form

### LINKED ISSUE #728: Code / create draft of 'contact us' page
Required for #723.

### PR DESCRIPTION
**Pull request by juliaelman**
This pull request is an updated version of the contact us form, based off of the updated navigation layout. In the old design, the contact us form was integrated into the page directly. This version creates a modal where the contact us lives and can be accessible on every page through the site. Here are some notes to take into consideration while reviewing:

- When reviewing the pull request, go to `localhost:3000/redesign` and click on `Contact Us` in the main navigation. 
-  While this is not best practice, I spoke with the dev team and we decided to move forward with commenting out the two failing homepage tests for now. The application is going through some major reconstruction at the moment and we need to re-think we way we re-do our integration tests overall //cc @yozlet @harrisj 

Here is a short clip to see the interactions of the working local version of the form:

tbw8l7n7ju

Fixes #728

### CODE REVIEW

**Comment by yozlet** [comment]
Nifty! Just a few points...

  1. Should we be asking the user to click again to close the modal after they've sent the message? I wonder if it might be better to have the modal roll up to a small confirmation message while re-enabling the rest of the page.
  2. Those Hound warnings about colour literals being kept to variables sound like a good idea to me, but I get that we're in the middle of a CSS refactor. What do you have in mind for those?
  3. I'd really really rather not ship new JS-powered functionality without some supporting tests. But these might be a bit of a pain. I'm focused on Cloud Foundry stuff right now but I'm happy to dive into the tests for this in the next day or two.

**Comment by yozlet** [comment]
Sorry, I now realise that point 1 is about #728, and irrelevant to the implementation.

**Comment by yozlet** [comment]
OK, am having a quick go at the tests now. For future reference: If you need to disable broken tests but want to keep them on the radar for future fixing, set them to pending. For example:

```ruby
  # TODO: Disabling these tests for now until we have a more
  # solidified version of the app to create solid integration tests.

  context 'without javascript' do
    pending "Waiting for app refactoring" do
      it_behaves_like 'user contact form' do
        let(:display_message) { @home_page.contact_flash_no_js }
      end
    end
  end
```

(In writing this it took me a couple of attempts to get the right usage of [`pending`](https://www.relishapp.com/rspec/rspec-core/v/3-3/docs/pending-and-skipped-examples/pending-examples) that wouldn't break the tests, so it's a bit hairy. Using one of the versions of [`skip`] might be easier. The point here is that skipped/pending tests show up as a kind of TODO list in the run results.)

**Comment by juliaelman** [comment]
Thanks for the review @yozlet! Here are some responses to your comments:

1) Sounds like this is addressed and we're good - thanks!
2) Yup! I mentioned the following in Slack, but the "changing colors into variables" bit, is something that will be part of the beautiful SMACSS integration I started on this branch: https://github.com/18F/myusa/tree/feature/initial-signin-flow-work Once we start the cascade of work we are currently doing, we'll eventually get to this state of having variables for colors. This is also something I demonstrated to the team during a retro a few weeks back.
3) See my main comment on the reasoning behind commenting out these tests for now: https://github.com/18F/myusa/pull/741#issue-98070234 You are more than welcome to take a crack at it. Just a reminder that this work is upstream from https://github.com/18F/myusa/issues/723 and will need to be complete before that work can be merged in.

**Comment by yozlet** [comment]
Where did this `modal-window.js` come from? It would be good to have a reference back to the original so we can bring it up to date if needed.

**Comment by yozlet** [comment]
OK, am going to merge this to unblock progress. We should add a credit link for the modal code somewhere (as per Melody's recent open source guide) and I'll do the contact form tests once the front-end refactor is complete.

**Comment by juliaelman** [comment]
@yozlet thanks for your review! 

The modal JS was a recommendation from @nickbristow to assist with the accessibility issues typically have. The original location for the repo and code is located here: https://github.com/gdkraus/accessible-modal-dialog. I'll add a link to this repo in the JS file and re-submit a PR with that change. Please let me know if you'd like me to post that link somewhere else! (e.g. README.md, Wiki, etc.)

**Pull request merged**
