### PR TITLE
Front end implementation of new design of permissions page.

### PR DESCRIPTION
**Pull request by adelevie**
cc @juliaelman 

Visit /permissions to view the page.

You can modify the data sent to the template by manipulating the `@pre_auth` object in the `redesign` method in `app/controllers/oauth/authorizations_controller.rb`.

### CODE REVIEW

**Comment by adelevie** [comment]
Found two WCAAG 2.0 AA issues with the HTML Code Sniffer:

screen shot 2015-05-13 at 10 46 28 am
screen shot 2015-05-13 at 10 46 09 am



@nickbristow should these be addressed?

**Comment by adelevie** [comment]
screen shot 2015-05-13 at 10 49 55 am

Could (or should) we increase the font size of the input text?

**Comment by nickbristow** [comment]
Good catch. I was just looking at functionality. Doh!

On Wednesday, May 13, 2015, Alan deLevie <notifications@github.com> wrote:

> [image: screen shot 2015-05-13 at 10 49 55 am]
> <https://cloud.githubusercontent.com/assets/86790/7613261/b753d8ac-f95d-11e4-86ef-00d51b8b0e73.png>
>
> Could (or should) we increase the font size of the input text?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/myusa/pull/638#issuecomment-101697932>.
>


-- 
Nick Bristow
18f <http://18f.gsa.gov> Innovation Specialist
Nick.Bristow@gsa.gov

**Comment by adelevie** [comment]
No worries, @nickbristow! It's a good reason we should have automated testing :)

I'm happy to fix these. Ping me if you have a minute or two to discuss.

**Comment by nickbristow** [comment]
you in the office? I'll be in this afternoon.

Nick Bristow
18f <http://18f.gsa.gov> Innovation Specialist
Nick.Bristow@gsa.gov

**Comment by adelevie** [comment]
I'm here.

**Comment by juliaelman** [comment]
@adelevie @nickbristow made a quick fix for the contrast ratio issue! Want to double check?

**Comment by juliaelman** [comment]
@adelevie @yozlet I made a few solves for the errors Snap CI returned. The others are due to a re-config of the overall HTML/CSS in the code due to new design direction. The test failures are primarily coming from here: https://github.com/18F/myusa/blob/devel/spec/features/doorkeeper/oauth_spec.rb

I am outlining them below and want to make sure the solutions sound fair before moving forward with these changes:

**1) OAuth Authorization when logged in with lots of scopes displays the proper scopes**
*/spec/features/doorkeeper/oauth_spec.rb:244*
There are a lot of scopes that got removed from this design, but am not sure if they should also be removed from tests. I am assuming that information will still be accessible, but am not sure if it's something we should/need to test for.

**2) OAuth Authorization when logged in with valid url params user can deny by clicking "head back to" link**
*/spec/features/doorkeeper/oauth_spec.rb:149*
I think that we should just remove this entirely, as that is not included in the re-design.

**3) OAuth Authorization when logged in with valid url params user can switch to another user**
*/spec/features/doorkeeper/oauth_spec.rb:119*
It doesn't look like we're providing access to switch to another user anymore. Recommendation to remove.

**4) OAuth Authorization when logged in with valid url params profile data is invalid user cannot save or authorize**
*/spec/features/doorkeeper/oauth_spec.rb:191*
This is creating an error b/c we no longer have phone number as a field. Recommendation to remove.

**5) OAuth Authorization when logged in with valid url params app has TOS links page displays links to TOS**
*/spec/features/doorkeeper/oauth_spec.rb:157*
This is creating an error b/c we no longer have phone number as a field. Recommendation to remove.

There are a few other errors, but believe those due to the re-config Alan did to help make this run locally. Let me know what you all think and am happy to implement these changes! :+1:

**Comment by yozlet** [comment]
Need sign-off from @mkhandekar & @esgoodman on the above feature changes that the test failures are showing up. If those feature changes are good, then we should fix or remove those tests.

Which scopes are being removed? If they're being removed from all interactions then we should remove them from the rest of the code. This may require an API version bump.

**Comment by adelevie** [comment]
I don't think we're removing scopes here. Are we?

My understanding is that the design only covered certain scopes (because why design a page with every combination of available scopes...), but we're still to not change our scopes. Or not?

**Comment by juliaelman** [comment]
@adelevie @yozlet thanks for the feedback on these! 

@esgoodman @mkhandekar here are the scopes + other page features that we need further clarification on. Please let us know how best to move forward to completing this PR with the design outlined in #608.

- Remove tests for a the following completed scope list: ["Email Address", "Title", "First Name", "Middle Name", "Last Name", "Suffix", "Home Address", "Home Address (Line 2)", "Zip Code", "Phone Number", "Gender", "Marital Status", "Are you a Parent?", "Are you a Student?", "Are you a Veteran?", "Are you Retired?", "Allow the application send you notifications via MyUSA"]
- Remove any tests for the "head back to", as it has been removed in the new design.
- Remove any tests for "This is not me" links to switch to a new user
- Remove any tests for phone number
- Remove any tests for link to "Terms of Service"

**Comment by mkhandekar** [comment]
Generally, the Permissions page that we designed if an example of what this page could work like. The scopes we used are a tiny fraction of what agencies might ask. My hunch is to keep all scopes that we have because I imagine they will be used in the future. If the current task is to remove these scopes _just for this pull request_ to eliminate test failures, then remove the scopes. Would love @esgoodman's thoughts too. 

> Remove tests for a the following completed scope list: ["Email Address", "Title", "First Name", "Middle Name", "Last Name", "Suffix", "Home Address", "Home Address (Line 2)", "Zip Code", "Phone Number", "Gender", "Marital Status", "Are you a Parent?", "Are you a Student?", "Are you a Veteran?", "Are you Retired?", "Allow the application send you notifications via MyUSA"]

It's on my list to design a permissions page with all of these items so we know what the extreme could look like, so I would not remove these tests.

> Remove any tests for the "head back to", as it has been removed in the new design.

Is this "head back to" Agency website? If so, then we have 2 screens in the [upcoming sign in flow](https://projects.invisionapp.com/share/QV2ZZFKR3#/screens/78398199/comments) where this is possible. 

> Remove any tests for "This is not me" links to switch to a new user

Thanks for reminding me of this functionality. It's sounds valuable, so I will incorporate this in the sign in flow / permissions, unless anyone objects?

> Remove any tests for phone number

What is this? The app asks for visitor's phone number?

> Remove any tests for link to "Terms of Service" and "This is creating an error b/c we no longer have phone number as a field. Recommendation to remove."

Why are the scopes for phone number and TOS connected? I don't understand. Also, I imagine we will definitely have a TOS in the future, so not clear on reasons to remove.

cc: @yozlet @adelevie @juliaelman

**Comment by esgoodman** [comment]
I agree with everything what @mkhandekar [said](https://github.com/18F/myusa/pull/638#issuecomment-102456345)

And specifically, I agree that: _If the current task is to remove these scopes just for this pull request to eliminate test failures, then remove the scopes_. We are keeping track of [which scopes each integrator needs, and when](https://docs.google.com/a/gsa.gov/spreadsheets/d/1Nl_TPX3P7gZ3FjLEM02JHuNp1tUSobVo5Iyf3EuX6sw/edit?usp=sharing) and it looks like we'll need all the scopes listed above up and running by June.

**Comment by mkhandekar** [comment]
For reference: [here are all the scopes](https://github.com/18F/myusa/issues/608#issuecomment-103548774).

**Comment by adelevie** [comment]
Current status:
screen shot 2015-05-19 at 11 33 33 am

**Comment by adelevie** [comment]
Some dev notes:

 Valid params (what I need to make):

```ruby
 {"utf8"=>"✓",
 "authenticity_token"=>"9fJexg9/Q0SKmFMmNEp3quuFfEzA5bqcsMU/7JqWr2w=",
 "client_id"=>"3ea02008992b6e8e178d6b609d3388ad929972134afb3f438c311f5a4cd71e6b",
 "redirect_uri"=>"http://localhost:9292/auth/myusa/callback",
 "state"=>"c61d0f4aeb3832fc142bb3a396673136bc55cc9423d02bab",
 "response_type"=>"code",
 "original_scope"=>"profile.email profile.first_name profile.last_name",
 "scope"=>["profile.email", "profile.first_name", "profile.last_name"],
 "user_id"=>"1",
 "allow"=>"1",
 "commit"=>"Allow Access",
 "action"=>"create",
 "controller"=>"oauth/authorizations"}
```
 
 Invalid params (what I have now):

 ```ruby
 {"utf8"=>"✓",
 "authenticity_token"=>"9fJexg9/Q0SKmFMmNEp3quuFfEzA5bqcsMU/7JqWr2w=",
 "client_id"=>"3ea02008992b6e8e178d6b609d3388ad929972134afb3f438c311f5a4cd71e6b",
 "redirect_uri"=>"http://localhost:9292/auth/myusa/callback",
 "state"=>"99836440f6c8988d53d2ab955702dd77dd65ffbb16669c09",
 "response_type"=>"code",
 "original_scope"=>"profile.email profile.first_name profile.last_name",
 "scope"=>["on", "on", "on"],
 "user_id"=>"1",
 "allow"=>"1",
 "commit"=>"Allow",
 "action"=>"create",
 "controller"=>"oauth/authorizations"}
```

**Comment by adelevie** [comment]
To get to the permissions screen locally:

Just to see the design (e.g. not functioning):

- `http://localhost:3000/permissions` (this route will be removed before the PR is merged)

To actually run the thing:

1. Set up a local OAuth-consuming app (Sinatra quickstart: https://github.com/18F/omniauth-myusa/tree/master/example)
2. `localhost:9292`
3. Click connect with MyUSA
4. Choose Google Option

To debug the form params, you can stick a `binding.pry` call in `authorizations_controller#create`.

**Comment by harrisj** [comment]
I had to add a `layout :redesign` to the controller method to make it render correctly with the stylesheet. Do we want to rename the layout to have a different name?

**Comment by juliaelman** [comment]
@harrisj I think we can leave it as `layout :redesign` for now, as we use this naming convention for transferring from the old to the new layout.

**Comment by harrisj** [comment]
:+1: if you are good to go, I am!

**Comment by juliaelman** [comment]
:rocket:

**Pull request merged**
